In [ ]:
import numpy as np

In [ ]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [ ]:
len(dir(np))

532

In [ ]:
a=np.array([10,14,24,35,60])
print(a)
print(a.ndim)  # 1 d
print(a.shape)  # 5 rows

[10 14 24 35 60]
1
(5,)


In [ ]:
print(a[2])

24


In [ ]:
t=[]
for  i in range(1,11):
  t.append(i)
a=np.array(t)
print(a)
print(a.ndim)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [ ]:
print(a[5])

6


2d data

In [ ]:
# 2d data

a=np.array([[10,3,6],[4,5,8],[9,2,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)  # totsl values

[[10  3  6]
 [ 4  5  8]
 [ 9  2  6]]
2
(3, 3)
9


In [ ]:
print(a[1][2])

8


In [ ]:
# 1d to 2d
a=np.array([10,3,4,6,8,54])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

print()

b=a.reshape(2,3)
print(b)
print(b.ndim)
print(b.shape)

[10  3  4  6  8 54]
1
(6,)
6

[[10  3  4]
 [ 6  8 54]]
2
(2, 3)


In [ ]:
# arange
a=np.arange(1,11)
print(a)
print(a.ndim)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [ ]:
# 1d to 2d
a=np.arange(1,11)
print(a)
print(a.ndim)
print(a.shape)

print()

b=a.reshape(2,5)
print(b)
print(b.ndim)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)


In [ ]:
print(b[1][3])

9


In [ ]:
a=np.arange(1,61).reshape(10,6)
print(a)
print(a.ndim)
print(a.shape)
print(a[4][3])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2
(10, 6)
28


In [ ]:
# 1d to 3d
a=np.arange(1,61)
print(a)
print(a.ndim)
print(a.shape)

print()

b=a.reshape(5,2,6)
print(b)
print(b.ndim)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
(60,)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3
(5, 2, 6)


In [ ]:
print(b[2][1][4])

35


In [ ]:
a=np.arange(1,61).reshape(5,2,6)
print(a)
print(a.ndim)
print(a.shape)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3
(5, 2, 6)


In [ ]:
print(a[3][0][3])

40


In [ ]:
a=np.array([2,7,9,4,5,8])
print(a)
print(a.ndim)
print(a.shape)

b=a.reshape(-1,1) ####################
print(b)
print(b.ndim)
print(b.shape)

[2 7 9 4 5 8]
1
(6,)
[[2]
 [7]
 [9]
 [4]
 [5]
 [8]]
2
(6, 1)


In [ ]:
a=np.arange(1,7)
print(a)
print(a.ndim)
print(a.shape)

b=a.reshape(-1,1) ###
print(b)
print(b.ndim)
print(b.shape)

[1 2 3 4 5 6]
1
(6,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
2
(6, 1)


In [ ]:
a=np.arange(1,7).reshape(-1,1)
print(a)
print(a.ndim)
print(a.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
2
(6, 1)


In [ ]:
a=np.array([2,7,9,4,5,8])
print(a)
print(a.ndim)
print(a.shape)

b=a.reshape(1,-1) ####################
print(b)
print(b.ndim)
print(b.shape)

[2 7 9 4 5 8]
1
(6,)
[[2 7 9 4 5 8]]
2
(1, 6)


In [ ]:
a=np.arange(1,7)
print(a)
print(a.ndim)
print(a.shape)

b=a.reshape(1,-1)
print(b)
print(b.ndim)
print(b.shape)

[1 2 3 4 5 6]
1
(6,)
[[1 2 3 4 5 6]]
2
(1, 6)


In [ ]:
a=np.arange(1,7).reshape(1,-1)
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3 4 5 6]]
2
(1, 6)


In [ ]:
# 2d to 3d

a=np.array([[10,3,6],[4,5,8],[9,2,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

b=a.reshape(1,3,3)
print(b)
print(b.ndim)
print(b.shape)

[[10  3  6]
 [ 4  5  8]
 [ 9  2  6]]
2
(3, 3)
9
[[[10  3  6]
  [ 4  5  8]
  [ 9  2  6]]]
3
(1, 3, 3)


In [ ]:
a=np.arange(1,21)  # 1d
print(a)
print(a.ndim)
print(a.shape)

b=a.reshape(5,4)  # 2d
print(b)
print(b.ndim)
print(b.shape)

c=b.reshape(5,2,2)  # 3d
print(c)
print(c.ndim)
print(c.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
2
(5, 4)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]
3
(5, 2, 2)


In [ ]:
a=np.arange(1,21).reshape(5,2,2)
print(a)
print(a.ndim)
print(a.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]
3
(5, 2, 2)


zeros

In [7]:
import numpy as np

a=np.zeros((5,4))
print(a)

print()

print(a.dtype)

print()

b=np.zeros((5,4),dtype=np.int32)
print(b)
print(b.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

float64

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


ones

In [9]:
a=np.ones((5,4))
print(a)
b=np.ones((5,4),dtype=np.int32)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


full

In [10]:
a=np.full((5,4),7)
print(a)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


eye

In [11]:
a=np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [12]:
a=np.eye(2,dtype=np.int32)
print(a)

[[1 0]
 [0 1]]


In [13]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
a=np.eye(4,dtype=np.int32)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


diag

In [15]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [16]:
a=np.diag([11,22,33,44])
print(a)

[[11  0  0  0]
 [ 0 22  0  0]
 [ 0  0 33  0]
 [ 0  0  0 44]]


randint

In [21]:
a=np.random.randint(10,50)
print(a)

30


In [24]:
a=np.random.randint(10,50,3)
print(a)

[34 21 42]


rand

In [26]:
a=np.random.rand(5,4)
print(a)

[[0.71762206 0.21644139 0.70488721 0.55974355]
 [0.78574502 0.67026759 0.48951211 0.73261326]
 [0.44547138 0.30209179 0.86724379 0.15404981]
 [0.4358246  0.05035573 0.37463074 0.23189517]
 [0.78342974 0.3626362  0.10495584 0.37202487]]


random

In [28]:
a=np.random.random((5,4))
print(a)

[[0.94622767 0.09691107 0.54236717 0.15676649]
 [0.63207623 0.58619356 0.03800207 0.50043634]
 [0.10077736 0.71933396 0.11060492 0.17425053]
 [0.7315588  0.66733344 0.22363678 0.847989  ]
 [0.42817428 0.63206271 0.95640168 0.65875521]]


randn

In [36]:
a=np.random.rand(5,6)
print(a)

[[0.63326229 0.46211598 0.49068195 0.59580447 0.42541441 0.43941283]
 [0.08575323 0.0375187  0.40178907 0.38633196 0.96729605 0.5778212 ]
 [0.65580002 0.55085709 0.80140577 0.44067474 0.80632178 0.44067429]
 [0.94422283 0.17642355 0.82247681 0.89894927 0.89797209 0.53077695]
 [0.46613022 0.88232853 0.4405563  0.46472938 0.78761026 0.39950551]]


ravel

In [40]:
a=np.array([[10,3,6],[4,5,8],[9,2,6]])
print(a)
print(a.ndim)
print(a.shape)

b=np.ravel(a)
print(b)
print(b.ndim)
print(b.shape)

[[10  3  6]
 [ 4  5  8]
 [ 9  2  6]]
2
(3, 3)
[10  3  6  4  5  8  9  2  6]
1
(9,)


transpose

In [42]:
a=np.array([[10,3,6],[4,5,8],[9,2,6]])
print(a)

b=np.transpose(a)
print(b)

[[10  3  6]
 [ 4  5  8]
 [ 9  2  6]]
[[10  4  9]
 [ 3  5  2]
 [ 6  8  6]]


concat

In [47]:
a=np.array([[10,3,6],[4,5,8],[9,2,6]])
b=np.array([[10 , 4 , 9],[ 3 , 5,  2],[ 6  ,8 , 6]])
print(a)
print()
print(b)
print()
c=np.concat((a,b))
print(c)


[[10  3  6]
 [ 4  5  8]
 [ 9  2  6]]

[[10  4  9]
 [ 3  5  2]
 [ 6  8  6]]

[[10  3  6]
 [ 4  5  8]
 [ 9  2  6]
 [10  4  9]
 [ 3  5  2]
 [ 6  8  6]]


axis=1  axis=0

In [49]:
a=np.array([[10,3,2],[1,6,4],[9,7,8]])
print(np.sum(a))

50


In [51]:
print(np.sum(a,axis=1))

[15 11 24]


In [53]:
print(np.sum(a,axis=0))

[20 16 14]


In [54]:
print(np.max(a))

10


In [55]:
print(np.min(a))

1


In [56]:
print(np.max(a,axis=1))

[10  6  9]


In [57]:
print(np.max(a,axis=0))

[10  7  8]


In [58]:
print(np.min(a,axis=1))

[2 1 7]


In [59]:
print(np.min(a,axis=0))

[1 3 2]


argmax  , argmin

In [60]:
print(np.argmax(a))

0


In [61]:
print(np.argmin(a))

3


In [62]:
print(np.argmax(a,axis=1))

[0 1 0]


In [63]:
print(np.argmax(a,axis=0))

[0 2 2]


In [64]:
print(np.argmin(a,axis=1))

[2 0 1]


In [66]:
print(np.argmin(a,axis=0))

[1 0 0]


repeat

In [72]:
a=np.arange(10,21)
print(a)
b=a.reshape(1,-1)
print(b)
print()
c=np.repeat(b,5,axis=0)
print(c)

[10 11 12 13 14 15 16 17 18 19 20]
[[10 11 12 13 14 15 16 17 18 19 20]]

[[10 11 12 13 14 15 16 17 18 19 20]
 [10 11 12 13 14 15 16 17 18 19 20]
 [10 11 12 13 14 15 16 17 18 19 20]
 [10 11 12 13 14 15 16 17 18 19 20]
 [10 11 12 13 14 15 16 17 18 19 20]]


math operations

In [74]:
a=np.array([[10,3,6],[4,5,8],[9,2,6]])
b=np.array([[10,4,9],[3,5,2],[6,8,6]])
print(np.add(a,b))

[[20  7 15]
 [ 7 10 10]
 [15 10 12]]


In [75]:
print(np.subtract(a,b))

[[ 0 -1 -3]
 [ 1  0  6]
 [ 3 -6  0]]


In [76]:
print(np.multiply(a,b))

[[100  12  54]
 [ 12  25  16]
 [ 54  16  36]]


matmul

In [77]:
a=np.array([[1,4],[7,6]])
b=np.array([[4,3,2],[1,8,6]])
print(np.matmul(a,b))

[[ 8 35 26]
 [34 69 50]]


for loop

In [78]:
a=np.array([[10,3,6],[4,5,8],[9,2,6]])
for i in a:
  for j in i:
    if j%2==0:
      print(j)

10
6
4
8
2
6
