In [2]:
import numpy as np
import pandas as pd

np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Selecting and retrieving Data

In [5]:
a=pd.Series(np.arange(5,23,3))
a

0     5
1     8
2    11
3    14
4    17
5    20
dtype: int64

In [7]:
b=pd.Series(range(30,100,5))
b

0     30
1     35
2     40
3     45
4     50
5     55
6     60
7     65
8     70
9     75
10    80
11    85
12    90
13    95
dtype: int64

In [13]:
a=pd.Series(np.arange(5,23,3),index=["row 0","row 1", "row 2", "row 3","row 4","row 5"])
a

row 0     5
row 1     8
row 2    11
row 3    14
row 4    17
row 5    20
dtype: int64

In [14]:
a=pd.Series(np.arange(3,8))
a

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [15]:
a=pd.Series([22,34,67,54,78])
a

0    22
1    34
2    67
3    54
4    78
dtype: int64

In [16]:
type(a)

pandas.core.series.Series

In [17]:
a

0    22
1    34
2    67
3    54
4    78
dtype: int64

In [18]:
a[3]

np.int64(54)

In [19]:
#slicing
a[1:4]

1    34
2    67
3    54
dtype: int64

In [20]:
a[1:]

1    34
2    67
3    54
4    78
dtype: int64

In [21]:
np.random.randn(36)

array([-1.18110669, -0.7489043 ,  1.09304186, -1.75061987,  0.45867688,
       -0.27204412, -0.18813757,  0.19510971,  1.06323389, -0.14336731,
       -0.47718632, -1.10879317, -0.67311377,  0.16796039,  2.09400584,
        0.76929981, -0.65158206,  0.55912949, -2.16079445, -0.711171  ,
       -0.05493991, -0.70698268, -1.67406715,  1.37724625,  1.14982078,
        1.67031203,  0.40663127, -1.18466992, -0.56439778,  1.54484533,
        0.95930541, -1.10926432, -1.0614507 ,  2.01148523, -0.52482075,
        0.89141118])

In [25]:
np.random.randint(10,34,(3,4))

array([[24, 29, 26, 31],
       [16, 22, 17, 15],
       [28, 14, 12, 14]])

In [30]:
#special indexer
ind=['row 1', 'row 2','row 3', 'row 4','row 5', 'row 6']
col=['col 1', 'col 2','col 3', 'col 4', 'col 5', 'col 6']
x=pd.DataFrame(np.random.rand(36).reshape((6,6)),index=ind,columns=col)
x

col 1     col 2     col 3     col 4     col 5     col 6
row 1  0.534987  0.125909  0.633979  0.592238  0.173579  0.238256
row 2  0.908900  0.312461  0.830905  0.655277  0.059926  0.242647
row 3  0.721685  0.461306  0.731664  0.688652  0.837881  0.941171
row 4  0.770302  0.671892  0.066964  0.051213  0.423744  0.787105
row 5  0.347438  0.452613  0.344534  0.475781  0.744416  0.927610
row 6  0.702900  0.542784  0.670749  0.610293  0.047079  0.430980

In [32]:
x.loc['row 1','col 3']

np.float64(0.6339792722871322)

In [34]:
x.loc[['row 1','row 5','row 6'],['col 2','col 5','col 6']]   # select multiple rows and cols

col 2     col 5     col 6
row 1  0.125909  0.173579  0.238256
row 5  0.452613  0.744416  0.927610
row 6  0.542784  0.047079  0.430980

In [35]:
x.loc[['row 2','row 5'],['col 4','col 6']]

col 4     col 6
row 2  0.655277  0.242647
row 5  0.475781  0.927610

In [37]:
x1=pd.DataFrame(np.random.rand(36).reshape(6,6))
x1

0         1         2         3         4         5
0  0.382072  0.372718  0.988538  0.176963  0.749649  0.143924
1  0.676800  0.160385  0.017354  0.366455  0.675670  0.001229
2  0.909329  0.661785  0.840553  0.932675  0.951272  0.012255
3  0.070491  0.696868  0.446562  0.653176  0.754702  0.329508
4  0.014112  0.089252  0.907446  0.652705  0.279035  0.529655
5  0.295208  0.309096  0.662141  0.326041  0.832017  0.843050

In [39]:
c=pd.DataFrame(range(8),index=['row 1', 'row 2','row 3', 'row 4','row 5', 'row 6','row 7', 'row 8'])
c

0
row 1  0
row 2  1
row 3  2
row 4  3
row 5  4
row 6  5
row 7  6
row 8  7

In [40]:
c>5

0
row 1  False
row 2  False
row 3  False
row 4  False
row 5  False
row 6  False
row 7   True
row 8   True

In [43]:
c[c>=4]

0
row 1  NaN
row 2  NaN
row 3  NaN
row 4  NaN
row 5  4.0
row 6  5.0
row 7  6.0
row 8  7.0

In [46]:
c[(c>=4) | (c<=3)]

0
row 1  0
row 2  1
row 3  2
row 4  3
row 5  4
row 6  5
row 7  6
row 8  7

In [47]:
c

0
row 1  0
row 2  1
row 3  2
row 4  3
row 5  4
row 6  5
row 7  6
row 8  7

In [48]:
x

col 1     col 2     col 3     col 4     col 5     col 6
row 1  0.534987  0.125909  0.633979  0.592238  0.173579  0.238256
row 2  0.908900  0.312461  0.830905  0.655277  0.059926  0.242647
row 3  0.721685  0.461306  0.731664  0.688652  0.837881  0.941171
row 4  0.770302  0.671892  0.066964  0.051213  0.423744  0.787105
row 5  0.347438  0.452613  0.344534  0.475781  0.744416  0.927610
row 6  0.702900  0.542784  0.670749  0.610293  0.047079  0.430980

In [49]:
x[x>0.4]

col 1     col 2     col 3     col 4     col 5     col 6
row 1  0.534987       NaN  0.633979  0.592238       NaN       NaN
row 2  0.908900       NaN  0.830905  0.655277       NaN       NaN
row 3  0.721685  0.461306  0.731664  0.688652  0.837881  0.941171
row 4  0.770302  0.671892       NaN       NaN  0.423744  0.787105
row 5       NaN  0.452613       NaN  0.475781  0.744416  0.927610
row 6  0.702900  0.542784  0.670749  0.610293       NaN  0.430980

removing Duplicates

In [50]:
# creating DataFrame using constructor
df_obj = pd.DataFrame({'col 1' : [1,2,2,3,3,3,4,4],
                    'col 2' : ['a','b','b','c','c','c','d','c'],
                    'col 3' : ['A','B','B','C','C','C','D','D']})
df_obj

col 1 col 2 col 3
0      1     a     A
1      2     b     B
2      2     b     B
3      3     c     C
4      3     c     C
5      3     c     C
6      4     d     D
7      4     c     D

In [51]:
#what if you col names are same.. it over writes
pd.DataFrame({'col 1' : [1,2,2,3,3,3,4,4],
                    'col 2' : ['a','b','b','c','c','c','d','c'],
                    'col 2' : ['A','B','B','C','C','C','D','D']})


col 1 col 2
0      1     A
1      2     B
2      2     B
3      3     C
4      3     C
5      3     C
6      4     D
7      4     D

In [53]:
df_obj

col 1 col 2 col 3
0      1     a     A
1      2     b     B
2      2     b     B
3      3     c     C
4      3     c     C
5      3     c     C
6      4     d     D
7      4     c     D

In [55]:
df2=pd.DataFrame(np.arange(36).reshape(6,6))
df2


0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [56]:
df3=pd.DataFrame(np.arange(15).reshape(5,3))
df3

0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [60]:
pd.concat([df2,df3],axis=0).reset_index(drop=True)  #using concatenate:


0   1   2     3     4     5
0    0   1   2   3.0   4.0   5.0
1    6   7   8   9.0  10.0  11.0
2   12  13  14  15.0  16.0  17.0
3   18  19  20  21.0  22.0  23.0
4   24  25  26  27.0  28.0  29.0
5   30  31  32  33.0  34.0  35.0
6    0   1   2   NaN   NaN   NaN
7    3   4   5   NaN   NaN   NaN
8    6   7   8   NaN   NaN   NaN
9    9  10  11   NaN   NaN   NaN
10  12  13  14   NaN   NaN   NaN

In [62]:
n=pd.concat([df2,df3],axis=0)
n

0   1   2     3     4     5
0   0   1   2   3.0   4.0   5.0
1   6   7   8   9.0  10.0  11.0
2  12  13  14  15.0  16.0  17.0
3  18  19  20  21.0  22.0  23.0
4  24  25  26  27.0  28.0  29.0
5  30  31  32  33.0  34.0  35.0
0   0   1   2   NaN   NaN   NaN
1   3   4   5   NaN   NaN   NaN
2   6   7   8   NaN   NaN   NaN
3   9  10  11   NaN   NaN   NaN
4  12  13  14   NaN   NaN   NaN

In [66]:
n.drop([5],axis=1)

0   1   2     3     4
0   0   1   2   3.0   4.0
1   6   7   8   9.0  10.0
2  12  13  14  15.0  16.0
3  18  19  20  21.0  22.0
4  24  25  26  27.0  28.0
5  30  31  32  33.0  34.0
0   0   1   2   NaN   NaN
1   3   4   5   NaN   NaN
2   6   7   8   NaN   NaN
3   9  10  11   NaN   NaN
4  12  13  14   NaN   NaN

In [67]:
n.drop([2,5],axis=1)

0   1     3     4
0   0   1   3.0   4.0
1   6   7   9.0  10.0
2  12  13  15.0  16.0
3  18  19  21.0  22.0
4  24  25  27.0  28.0
5  30  31  33.0  34.0
0   0   1   NaN   NaN
1   3   4   NaN   NaN
2   6   7   NaN   NaN
3   9  10   NaN   NaN
4  12  13   NaN   NaN

NameError: name 'df' is not defined