In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(a.ndim)
print(a.shape,a.size)

[1 2 3 4]
1
(4,) 4


In [8]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a,a.ndim,a.shape,a.size)


[[1 2 3 4]
 [5 6 7 8]] 2 (2, 4) 8


difference between scalar , vector , Tensor

1 . Scalar = [1,2,3,4]
 2. Vector = [1 2] [3 4]

tensor = [[1,2] , [3,4]] # n dimensioal array ( numpy )

     [[5,6] , [8,9]]

Numpy ->

1 . tensforflow 2 . keras 3. Pytorch

In [11]:
for i in range(1,11):
  print(i,end=' ')

1 2 3 4 5 6 7 8 9 10 

In [12]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
a=np.array([1,2,3])
b=np.array([[2],[4]])
c=np.array([[[2],[5],[7]]])
print(a,a.ndim)
print(b,b.ndim)
print(c,c.ndim)

[1 2 3] 1
[[2]
 [4]] 2
[[[2]
  [5]
  [7]]] 3


methods

arange

In [15]:
a=np.arange(1,11)
print(a)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [16]:
a=np.arange(1,11,2)# last parameter is step size
# giving the gap 2 numbers
print(a)

[1 3 5 7 9]


In [18]:
a=np.arange(1,21,3)
print(a)

[ 1  4  7 10 13 16 19]


In [19]:
# using data type
a=np.arange(1,11,2,dtype=np.int32)
print(a)

[1 3 5 7 9]


In [20]:
a=np.arange(1,11,2,dtype=float)
print(a)

[1. 3. 5. 7. 9.]


linspace()
It is similar to the arrange function. However, it doesn?t allow us to specify the step size in the syntax.
Instead of that, it only returns evenly separated values over a specified period.
The system implicitly calculates the step size.
statistics -> std (standard deviations positions ) of the variable (column)
10 - 20 5 halfs = 12 , 14 , 16 , 18 , 20

In [21]:
#np.linspace(start, stop, num)
a=np.linspace(10,20,5)
print(a)
#20-10/5-1 = 10/4 = 2.5 , The interval between numbers is: 2.5

[10.  12.5 15.  17.5 20. ]


In [23]:
a=np.linspace(1,30,6)
print(a)

[ 1.   6.8 12.6 18.4 24.2 30. ]


zeros

In [26]:
a=np.zeros((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
a=np.zeros((2,4),dtype=np.int32)
print(a)

[[0 0 0 0]
 [0 0 0 0]]


ones

In [28]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
a=np.ones((2,3),dtype=np.int32)
print(a)

[[1 1 1]
 [1 1 1]]


In [30]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#using slicing operations

In [31]:
a=np.arange(1,11)
a[5:]=99
print(a)

[ 1  2  3  4  5 99 99 99 99 99]


In [32]:
a=np.arange(1,11)
print(a)
print(a[::-1])

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [33]:
print(list(range(10,100,5)))

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


1d 2d 3d arrays

In [35]:
a=np.arange(1,11)
print(a)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [36]:
a=np.arange(1,11).reshape(5,2)
print(a)
print(a.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2


In [46]:
a=np.arange(1,61).reshape(10,6)
print(a)
print(a.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2


In [47]:
print(a[4][1])

26


In [48]:
print(np.sum(a,axis=1))

[ 21  57  93 129 165 201 237 273 309 345]


In [49]:
print(np.sum(a,axis=0))

[280 290 300 310 320 330]


In [51]:
a=np.arange(1,61).reshape(5,2,6)
print(a)
print(a.ndim)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3


In [53]:
print(a[2][1][2])

33


In [52]:
print(np.sum(a))

1830


In [54]:
print(a.shape)

(5, 2, 6)


#random function:

In [56]:
a=np.random.randint(1,51)
print(a)   # genrates random int in the given range

28


In [61]:
a=np.random.randint(1,51,3)
print(a)

[35  2 29]


In [57]:
a=np.random.rand(3,2)
print(a)

[[0.4721299  0.55323769]
 [0.4064095  0.3559183 ]
 [0.10401643 0.94009996]]


In [58]:
a=np.random.random((3,2))
print(a)

[[0.48911723 0.04170895]
 [0.24442573 0.24871397]
 [0.4218304  0.23326175]]


In [59]:
a=np.random.randn(3,2)
print(a)

[[ 2.0558462  -0.08732767]
 [-0.1887158   0.62787118]
 [-1.96292008 -1.12059283]]


In [62]:
np.sqrt(120)

np.float64(10.954451150103322)

In [63]:
a=[1,2,3]
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


In [64]:
a=1
print(np.sin(a))

0.8414709848078965


In [65]:
b=9
print(np.cos(b))

-0.9111302618846769


# vertical stacking

In [70]:
a=np.arange(1,61).reshape(10,6)  # vertical stacking : place one array on top of the other: number of columns should match
print(a)
b=np.arange(61,121).reshape(10,6)
print(a)
c=np.vstack((a,b))
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
[[  1   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 13  14  15  16  17  18]
 [ 19  20  21  22  23  24]
 [ 25  26  27  28  29  30]
 [ 31  32  33  34  35  36]
 [ 37  38  39  40  41  42]
 [ 43  44  45  46  47  48]
 [ 49  50  51  52  53  54]
 [ 55  56  57  58  59  60]
 [ 61  62  63  64  65  66]
 [ 67  68  69  70  71  72]
 [ 73  74  75  76  77  78]
 [ 79  80  81  82  83  84]
 [ 85  86  87  88  89  90]
 [ 91  92  93  94  95  96]
 [ 97  98  99 100 101 102]
 [103 104 105 106 107 108]
 [109 110 111 112 113 114]
 [115 116 117 118 119 120]]


# horizontal stacking: one next to the other . number of rows of the 2 arrays should match.

In [72]:
print(np.hstack((a,b)))

[[  1   2   3   4   5   6  61  62  63  64  65  66]
 [  7   8   9  10  11  12  67  68  69  70  71  72]
 [ 13  14  15  16  17  18  73  74  75  76  77  78]
 [ 19  20  21  22  23  24  79  80  81  82  83  84]
 [ 25  26  27  28  29  30  85  86  87  88  89  90]
 [ 31  32  33  34  35  36  91  92  93  94  95  96]
 [ 37  38  39  40  41  42  97  98  99 100 101 102]
 [ 43  44  45  46  47  48 103 104 105 106 107 108]
 [ 49  50  51  52  53  54 109 110 111 112 113 114]
 [ 55  56  57  58  59  60 115 116 117 118 119 120]]


In [73]:
# diag

a=np.array([1,2,3])
print(np.diag(a))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [74]:
a=np.array([
    [1,2,3,4],
[20,30,59,70]
])
print(a)
a.ndim

[[ 1  2  3  4]
 [20 30 59 70]]


2

In [78]:
x=np.ravel(a)  # ravel changes 2d array to 1 d array
print(x)
print(x.ndim)

[ 1  2  3  4 20 30 59 70]
1


In [79]:
print(np.transpose(a))  # transpose matrix

[[ 1 20]
 [ 2 30]
 [ 3 59]
 [ 4 70]]


In [80]:
a=np.abs(-100)  # absolute value

print(a)

100


In [81]:
# concatenate

a=np.array([

    [1,2,3,4],[3,4,5,6]
])
b=np.array([

    [9,8,7,6],[6,5,4,3]
])

print(a)
print()
print(b)
c=np.concatenate((a,b))
c

[[1 2 3 4]
 [3 4 5 6]]

[[9 8 7 6]
 [6 5 4 3]]


array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [9, 8, 7, 6],
       [6, 5, 4, 3]])

In [82]:
# concatenate

a=np.array([

    [1,2,3,4],[3,4,5,6]
])
b=np.array([

    [9,8,7,6],[6,5,4,3]
])

print(a)
print()
print(b)
c=np.concat((a,b))
c

[[1 2 3 4]
 [3 4 5 6]]

[[9 8 7 6]
 [6 5 4 3]]


array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [9, 8, 7, 6],
       [6, 5, 4, 3]])

#Print the numpy version and the configuration

In [83]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [84]:
import numpy as np
print(np.__version__)

2.0.2


#How to find the memory size of any array

In [86]:
import numpy as np
n = np.zeros((4,4))
print(n)
print("%d bytes" % (n.size * n.itemsize))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
128 bytes


In [88]:
## identity matrix
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [90]:
a=np.eye(3,3,dtype=np.int32)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
