In [2]:
import numpy as np
a = np.array([[1,2,3,4] , [10,20,30,40] , [90,100,110,120]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[  1   2   3   4]
 [ 10  20  30  40]
 [ 90 100 110 120]]
2
(3, 4)
12


In [3]:
a=np.arange(1,82).reshape(3,3,9)
print(a)
print(a.ndim)
print(a[2][1][5])


[[[ 1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18]
  [19 20 21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34 35 36]
  [37 38 39 40 41 42 43 44 45]
  [46 47 48 49 50 51 52 53 54]]

 [[55 56 57 58 59 60 61 62 63]
  [64 65 66 67 68 69 70 71 72]
  [73 74 75 76 77 78 79 80 81]]]
3
69


In [25]:
a=np.array([11,44,54,78,33])
print(type(a))
print(a.dtype)  # which data type holding an array
print(a)
print(a.ndim)
print(a.shape,a.size)

<class 'numpy.ndarray'>
int64
[11 44 54 78 33]
1
(5,) 5


In [ ]:
print(a[0],a[2])

11 54


In [ ]:
a[0]=999  # changing element
print(a)

[999  44  54  78  33]


In [ ]:
a=np.array([[21,43,6,33,88],[111,22,65,98,78]])
print(a)
print(a.ndim,a.shape,a.size)
print(a[0][3])
print(a[1][2])

[[ 21  43   6  33  88]
 [111  22  65  98  78]]
2 (2, 5) 10
33
65


In [ ]:
a=np.zeros((2,2),dtype=np.int32)
print(a)

[[0 0]
 [0 0]]


In [ ]:
a=np.full((3,3),7)  # defaultly int for full
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
a=np.full((3,3),7,dtype=float)
print(a)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [ ]:
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.eye(3,3,dtype=np.int32)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a=np.ones((3,3),dtype=np.int32)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
a=np.random.random((3,3))
print(a)

[[0.28454077 0.05405615 0.36829865]
 [0.69001008 0.32164822 0.83729276]
 [0.43272317 0.23900996 0.05547976]]


array slicing

array indexing

In [ ]:
a = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(a)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [ ]:
print(a[2,:3])
print(a[2][-1])
print(a[2][3])
print(a[2][:3])

[31 32 33]
34
34
[31 32 33]


In [ ]:
x=a[:2,1:4]  # a[row_start:row_end, column_start:column_end]  (ending point (n-1))

print(x)

[[12 13 14]
 [22 23 24]]


In [ ]:
print(a[0,1])
print(a[0][1])

12
12


In [ ]:
a=np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(a)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [ ]:
print(a[1][:])
print(a[1,:])

[21 22 23 24]
[21 22 23 24]


In [ ]:
print(a[1:2,:])
print(a[1:2][:])

[[21 22 23 24]]
[[21 22 23 24]]


In [ ]:
print(a[:,1])  # 1d
print(a[:,1:2])  # 2d

[12 22 32]
[[12]
 [22]
 [32]]


In [ ]:
s=a[:,1]
print(s,s.shape)  # 1d
x=a[:,1:2]
print(x,x.shape)  # 2d

[12 22 32] (3,)
[[12]
 [22]
 [32]] (3, 1)


boolean

In [8]:
a=np.array([[11,12], [21, 22], [31, 32]])
print(a)

[[11 12]
 [21 22]
 [31 32]]


In [12]:
x=a>15
print(x)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
print(a[x])

[21 22 31 32]


datatypes

In [ ]:
a=np.array([11,12])
print(a.dtype)

int64


In [ ]:
a=np.array([11,12],dtype=np.int32)
print(a.dtype)

int32


In [ ]:
a=np.array([2.33,6.88])
print(a.dtype)

float64


In [ ]:
a=np.array([2.33,6.88],dtype=np.int32)  # float to int
print(a.dtype)
print(a)

int32
[2 6]


In [ ]:
a=np.array([11,12],dtype=float)  # int to float
print(a.dtype)
print(a)

float64
[11. 12.]


arithmatic **operations**

In [ ]:
x = np.array([[111,112],[121,122]])
y = np.array([[211.1,212.1],[221.1,222.1]])
print(x)
print(y)

[[111 112]
 [121 122]]
[[211.1 212.1]
 [221.1 222.1]]


In [ ]:
print(x+y)
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]
[[322.1 324.1]
 [342.1 344.1]]


In [ ]:
print(x-y)
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]
[[-100.1 -100.1]
 [-100.1 -100.1]]


In [ ]:
print(x*y)
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]
[[23432.1 23755.2]
 [26753.1 27096.2]]


In [ ]:
print(x/y)
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]
[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [ ]:
x=np.array([1,2,3,4])
print(x)
print(np.sqrt(x))  # square root
print(np.exp(x))   # exponent (e ** x)

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


statistics

In [13]:
a=10*np.random.random((4,5))
print(a)

[[7.42535642 6.58973087 3.37705857 9.70915317 9.96434698]
 [4.70341022 3.22562759 4.47527032 3.05057335 4.63430526]
 [9.06317649 2.22504055 1.94753953 9.31633242 9.2854226 ]
 [2.18849288 9.71487919 9.60921599 9.89480502 6.96056097]]


In [14]:
print(a.mean())

6.368014918910575


In [15]:
print(np.mean(a))

6.368014918910575


In [ ]:
print(a.mean(axis=1))

[3.33649086 4.13147015 6.19280956 2.86832233]


In [16]:
print(np.mean(a,axis=1))

[7.4131292  4.01783735 6.36750232 7.67359081]


In [ ]:
print(a.mean(axis=0))

[7.85288342 1.61262855 5.75598215 3.65381091 1.7860611 ]


In [ ]:
print(a.sum())

82.64546449638546


In [ ]:
print(np.median(a,axis=1))  # median

[0.68303674 3.56245522 5.41693346 1.51659615]


In [ ]:
a = np.array([[1,2,3] , [5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a.sum()

np.int64(24)

In [ ]:
a.mean()

np.float64(4.0)

In [ ]:
print(a.mean())

4.0


In [ ]:
print(np.median(a))  # median

4.0


In [ ]:
a.sum(axis=1)

array([ 6, 18])

In [ ]:
a.sum(axis=0)

array([ 6,  8, 10])

sorting

In [ ]:
a=np.random.rand(6)
print(a)
b=np.array(a)
b.sort()
print(b)

[0.69787061 0.16095609 0.33855679 0.55556484 0.52036448 0.86039815]
[0.16095609 0.33855679 0.52036448 0.55556484 0.69787061 0.86039815]


In [ ]:
a=[1,2,3,4]
a.reverse()
print(a)

[4, 3, 2, 1]


In [ ]:
a=np.array([1,2,1,4,2,1,4,2])
print(np.unique(a))

[1 2 4]


set operations

In [ ]:
a=np.array(['desk','chair','bulb'])
b=np.array(['lamp','bulb','chair'])
print(a,b)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [ ]:
print(np.intersect1d(a,b))

['bulb' 'chair']


In [ ]:
print(np.union1d(a,b))

['bulb' 'chair' 'desk' 'lamp']


In [ ]:
print(np.setdiff1d(a,b))  # elements in a that are not in b

['desk']


In [ ]:
print(np.in1d(a,b))  #which element of a is also in b

[False  True  True]


/tmp/ipython-input-243298282.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a,b))  #which element of a is also in b


Broadcasting:

In [ ]:
a=np.zeros((4,3))
print(a)
b=np.array([1,2,3])
print(b)
print()

print(a+b)# add to each row of 'start' using broadcasting

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 2 3]

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
c=np.array([0,1,2,3])
c=c.reshape(-1,1)
print(c)

[[0]
 [1]
 [2]
 [3]]


In [ ]:
print(a+c)# add to each column of 'start' using broadcasting


[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [ ]:
x=np.array([1])# this will just broadcast in both dimensions
print(a+x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = [0,1,0,2]
print(a+b)# add the two together using broadcasting


[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


binary format


In [ ]:
x = np.array([ 23.23, 24.24] )
np.save('an_array', x)  #Saves the array x to disk

np.load('an_array.npy') #File format: NumPy binary format (.npy) File name created automatically:
                        #Reads the .npy file from disk Loads the data back into memory Returns a NumPy array

array([23.23, 24.24])

Dot Product on Matrices and Inner Product on Vectors:

In [17]:
a = np.array([[1,1],[2,2]])
b = np.array([[3,4],[4,4]])
print(a.dot(b))
#First row of result:
#(1×3) + (1×4) = 7
#(1×4) + (1×4) = 8
#Second row of result:
#(2×3) + (2×4) = 14
#(2×4) + (2×4) = 16

[[ 7  8]
 [14 16]]


In [22]:
a=np.array([[1,4],[7,6]])
b=np.array([[4,3,2],[1,8,6]])
print(np.matmul(a,b))

[[ 8 35 26]
 [34 69 50]]


In [20]:
a=np.array([[1,4],[7,6]])
b=np.array([[4,3,2],[1,8,6]])
print(a.dot(b))

[[ 8 35 26]
 [34 69 50]]


In [ ]:
a=np.array([9 , 9 ])
b=np.array([10, 10])
print(a.dot(b))
print(np.dot(a,b))

180
180


sum

In [ ]:
a=np.array([[11,12],[21,22]])
print(np.sum(a))# add all members
print(np.sum(a,axis=1))  # rowwise sum
print(np.sum(a,axis=0)) # columnwise sum

66


Element-wise Functions:

For example, let's compare two arrays values to get the maximum of each

In [ ]:
a=np.random.randn(8)
print(a)

[-0.64154886  0.73257433  0.60694409 -0.06068517 -0.07443778  1.25792028
 -0.43243631  2.60373175]


In [ ]:
b=np.random.randn(8)
print(b)

[ 2.75986793  0.16113386  1.31297739 -1.02856834 -0.19154083  0.36053168
  1.01650776  1.26127262]


In [ ]:
print(np.maximum(a,b))

[ 2.75986793  0.73257433  1.31297739 -0.06068517 -0.07443778  1.25792028
  1.01650776  2.60373175]


Reshaping array:


In [ ]:
a=np.arange(20)
print(a)
print('-------')
b=a.reshape(4,5)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
-------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Transpose:

In [ ]:
a=np.array([[11,22],[33,44]])
b=np.transpose(a)
print(b)

[[11 33]
 [22 44]]
